version: '3'
services:
  mysql1:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password 
      - MYSQL_DATABASE=MyDB
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=b98eLkdGWz2dFGmmnbbzxq
    ports:
      - 3306:3306

  flask: 
   image: flask
   build:
     context: ./
     dockerfile: Dockerfile
   ports:
     - 5000:5000
   depends_on:
     - mysql1
   links:
     - mysql1 
